name: Build and Run Docker Image

on:
  push

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Stop and remove existing container
        run: |
         sudo docker container stop front-end || true
         sudo docker container rm front-end || true
      - name: Remove unused Docker images and build cache
        run: |
         sudo docker image prune --force || true
         sudo docker builder prune --force --all || true
      - name: Build Docker image
        run: sudo docker build -t my-docker-image .
      - name: Run Docker container
        run: sudo docker run -d --name front-end -p 3000:80 my-docker-image
      - name: Remove unused Docker images
        run: sudo docker image prune --force